# Generated by Django 6.1 on 2026-08-24 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_desc', models.CharField(max_length=255)),
                ('due_day', models.IntegerField()),
                ('grace_period_days', models.IntegerField(default=0)),
                ('penalty_classification', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'budget_item',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('total_members', models.IntegerField()),
                ('no_of_earners', models.IntegerField()),
                ('no_of_dependents', models.IntegerField()),
                ('housing_type', models.CharField(max_length=100)),
                ('daily_food_expense_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_food_expense_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_transport_expense_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_transport_expense_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('survival_threshold_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('survival_threshold_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'household',
            },
        ),
        migrations.CreateModel(
            name='IncomeFrequency',
            fields=[
                ('frequency_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'income_frequency',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'item_category',
            },
        ),
        migrations.CreateModel(
            name='Earner',
            fields=[
                ('earner_id', models.AutoField(primary_key=True, serialize=False)),
                ('earner_fname', models.CharField(max_length=100)),
                ('earner_lname', models.CharField(max_length=100)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, to='api.household')),
            ],
            options={
                'db_table': 'earner',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('range_amount', models.CharField(max_length=100)),
                ('income_startdate', models.DateField()),
                ('next_payday', models.DateField()),
                ('earner', models.ForeignKey(db_column='earner_id', on_delete=django.db.models.deletion.CASCADE, to='api.earner')),
                ('income_frequency', models.ForeignKey(db_column='income_frequency_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.incomefrequency')),
            ],
            options={
                'db_table': 'income',
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('budget_allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_due_date', models.DateField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('budget_amount_range', models.CharField(max_length=100)),
                ('budget_start_date', models.DateField()),
                ('budget_end_date', models.DateField()),
                ('budget_classification', models.CharField(blank=True, choices=[('Non-deferrable', 'Non-deferrable'), ('Deferrable', 'Deferrable')], max_length=20, null=True)),
                ('priority_level', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('period_half', models.CharField(blank=True, choices=[('1st Half', '1st Half'), ('2nd Half', '2nd Half'), ('Full Month', 'Full Month')], max_length=20, null=True)),
                ('bill_reminder', models.BooleanField(default=False)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='api.budgetitem')),
                ('income', models.ForeignKey(db_column='income_id', on_delete=django.db.models.deletion.CASCADE, to='api.income')),
            ],
            options={
                'db_table': 'budget_allocation',
            },
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='category',
            field=models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.itemcategory'),
        ),
    ]
