# Generated by Django 6.1 on 2026-09-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seed_income_frequencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='daily_food_expense_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='household',
            name='daily_food_expense_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='household',
            name='daily_transport_expense_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='household',
            name='daily_transport_expense_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='household',
            name='housing_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='household',
            name='no_of_dependents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='household',
            name='no_of_earners',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='household',
            name='survival_threshold_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='household',
            name='survival_threshold_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='household',
            name='total_members',
            field=models.IntegerField(default=0),
        ),
    ]
