# Generated by Django 6.1 on 2026-09-18 05:18

from django.db import migrations


# Common bill items every household starts with.
# Format: (category_desc, item_desc, due_day, grace_period_days, penalty_classification)
DEFAULT_BUDGET_ITEMS = [
    ('Utilities',      'Electricity',    15, 0, True),
    ('Utilities',      'Water',          20, 3, True),
    ('Utilities',      'Gas',            25, 0, True),
    ('Housing',        'Rent',            1, 0, True),
    ('Loans',          'Bank Loan',      10, 5, True),
    ('Communication',  'Internet',       28, 5, True),
    ('Communication',  'Mobile Plan',    25, 3, True),
    ('Transportation', 'Fuel',            5, 0, False),
    ('Education',      'Tuition Fee',    15, 0, True),
    ('Food',           'Groceries',      10, 0, False),
    ('Personal',       'Shopping',        0, 0, False),
]


def seed_budget_items(apps, schema_editor):
    ItemCategory = apps.get_model('api', 'ItemCategory')
    BudgetItem = apps.get_model('api', 'BudgetItem')

    for cat_desc, item_desc, due_day, grace, penalty in DEFAULT_BUDGET_ITEMS:
        try:
            category = ItemCategory.objects.get(category_desc=cat_desc)
        except ItemCategory.DoesNotExist:
            # Skip this item if its category wasn't seeded
            continue

        BudgetItem.objects.get_or_create(
            item_desc=item_desc,
            category=category,
            defaults={
                'due_day': due_day,
                'grace_period_days': grace,
                'penalty_classification': penalty,
            }
        )


def unseed_budget_items(apps, schema_editor):
    """Reverse — removes only the default items, leaves custom ones alone."""
    BudgetItem = apps.get_model('api', 'BudgetItem')
    descs = [b[1] for b in DEFAULT_BUDGET_ITEMS]
    BudgetItem.objects.filter(item_desc__in=descs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_household_daily_food_expense_max_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_budget_items, unseed_budget_items),
    ]