# Generated by Django 6.1 on 2026-09-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_seed_budget_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
