# Generated by Django 6.1 on 2026-09-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_budgetallocation_is_paid_budgetallocation_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
