# Generated by Django 6.1 on 2026-09-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_household_setup_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='rule_applied',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
