# Generated by Django 6.1 on 2026-10-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_household_no_of_children_household_no_of_seniors'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payday_day_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='payday_day_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='payday_weekday',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
