# Generated by Django 6.1 on 2026-10-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_income_payday_day_1_income_payday_day_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('biller_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('city', models.CharField(default='Cagayan de Oro', max_length=100)),
                ('keywords', models.CharField(blank=True, default='', max_length=255)),
                ('grace_period_days', models.IntegerField(default=0)),
                ('has_penalty', models.BooleanField(default=True)),
                ('rules_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'biller',
            },
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='reminder_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='biller',
            field=models.ForeignKey(blank=True, db_column='biller_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.biller'),
        ),
    ]
