# Generated by Django 6.1 on 2026-10-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_biller_budgetitem_is_daily_budgetitem_reminder_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='location',
            field=models.CharField(default='Cagayan de Oro', max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='budget_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='budget_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='due_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
