# Generated by Django 6.1 on 2026-10-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_relax_models_and_add_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='deferred_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
