# Generated by Django 6.1 on 2026-10-10 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_budgetallocation_deferred_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('dependent_id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=20)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='api.household')),
            ],
            options={
                'db_table': 'dependent',
            },
        ),
    ]
